import { NgModule } from '@angular/core';
import { MdePopoverModule } from '@material-extended/mde';

import {
    MatToolbarModule,
    MatIconModule,
    MatCardModule,
    MatFormFieldModule,
    MatInputModule,
    MatBadgeModule,
    MatSelectModule,
    MatTableModule,
    MatButtonModule,
    MatDialogModule,
    MatRadioModule,
    MatTooltipModule,
    MatAutocompleteModule,
    MatListModule,
    MatGridListModule,
    MatButtonToggleModule,
    MatSidenavModule,
    MatCheckboxModule,
    MatSlideToggleModule,
    MatChipsModule,
  } from '@angular/material';

@NgModule({
  imports: [
    MatToolbarModule,
    MatIconModule,
    MatCardModule,
    MatFormFieldModule,
    MatInputModule,
    MatBadgeModule,
    MatSelectModule,
    MatTableModule,
    MatButtonModule,
    MatDialogModule,
    MatRadioModule,
    MatTooltipModule,
    MatAutocompleteModule,
    MdePopoverModule,
    MatListModule,
    MatGridListModule,
    MatButtonToggleModule,
    MatSidenavModule,
    MatCheckboxModule,
    MatSlideToggleModule,
    MatChipsModule,
  ],
  exports: [
    MatToolbarModule,
    MatIconModule,     
    MatCardModule,
    MatFormFieldModule,
    MatInputModule,
    MatBadgeModule,
    MatSelectModule,
    MatTableModule,
    MatButtonModule,
    MatDialogModule,
    MatRadioModule,
    MatTooltipModule,
    MatAutocompleteModule,
    MatListModule,
    MatGridListModule,
    MatButtonToggleModule,
    MatSidenavModule,
    MdePopoverModule,
    MatCheckboxModule,
    MatSlideToggleModule,
    MatChipsModule
  ]
})
export class MaterialModule {}